---

name: "GitHub Action: Self-Test"

on:
  push:

env:
  PRODUCT_VERSION: "0.16.0"

jobs:
  setup-boundary:
    name: Test `setup-boundary`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Setup `boundary` (using local GitHub Action)
        uses: "./"
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Print `$PATH` for `boundary`
        run: which boundary

      - name: Print `boundary` version
        run: boundary version

      - name: Validate `boundary` version is accurate
        run: "boundary version | grep --silent '  Version Number:      ${{ env.PRODUCT_VERSION }}'"

      - name: Setup `boundary` with an invalid version (using local GitHub Action)
        uses: "./"
        id: invalid_version
        with:
          version: "invalid_version"
        continue-on-error: true

      - name: Validate invalid version failed
        if: steps.invalid_version.outcome == 'success'
        run: echo "Installing an invalid version expected to fail but did not" && exit 1

      - name: Setup `boundary` with `latest` version (using local GitHub Action)
        uses: "./"
        id: latest_version

      - name: Print `boundary` version
        run: boundary version
