name: compliance

on:
  push:

permissions:
  contents: read

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2
      - run: copywrite headers --plan
      - run: copywrite license --plan
