---
name: "HashiCorp: Compliance"

on:
  push:

permissions:
  contents: read

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3

      - run: copywrite headers --plan

      - run: copywrite license --plan
